import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // 前端开发侧边栏
  frontendSidebar: [
    'frontend/intro',
    {
      type: 'category',
      label: 'HTML & CSS',
      items: [
        'frontend/html-css/basics',
      ],
    },
    {
      type: 'category',
      label: 'JavaScript',
      items: [
        'frontend/javascript/basics',
      ],
    },
  ],

  // 算法与数据结构侧边栏 - 使用自动生成
  algorithmSidebar: [
    {
      type: 'autogenerated',
      dirName: 'algorithm',
    },
  ],

  // 学习笔记侧边栏
  notesSidebar: [
    'notes/intro',
    {
      type: 'category',
      label: '技术笔记',
      items: [
        'notes/tech/summary',
        'notes/tech/automation-system-architecture',
        'notes/tech/open-platform-architecture',
        'notes/tech/permission_public',
        'notes/tech/condition_model',
        'notes/tech/stamp_cache'
      ],
    },
  ],
};

export default sidebars;
